/* Fit the Student - level data: each gap's fixed size and the padding, border and margin its story demands. */
const FIT_STUDENT_CATEGORIES = [
  {
    id: "settling-in",
    name: "Settling In",
    color: "#2563eb",
    levels: [
      {
        id: "fs01",
        difficulty: "easy",
        student: "Maya",
        badge: "Maya &middot; 10B",
        left: "Locker 11",
        right: "Locker 13",
        hazard: "Wet paint",
        brief:
          "Maya has been given the last free space in locker bay 12. Locker 11 and locker 13 are bolted to the floor and will not move for anybody, so the gap between them stays exactly 320px wide and 200px tall no matter what you do.",
        gap: { width: 320, height: 200 },
        require: { padding: 10, border: 5, margin: 15 },
        boxSizing: "content-box",
      },
      {
        id: "fs02",
        difficulty: "easy",
        student: "Tomas",
        badge: "Tomas &middot; 10A",
        left: "Bench",
        right: "Bin store",
        hazard: "Fresh varnish",
        brief:
          "The courtyard bench and the bin store leave one 300px by 180px space between them, and Tomas has to wait there for the bus. The bench is concrete and the bin store is brick, so the space is not getting any larger.",
        gap: { width: 300, height: 180 },
        require: { padding: 12, border: 4, margin: 14 },
        boxSizing: "content-box",
      },
      {
        id: "fs03",
        difficulty: "easy",
        student: "Priya",
        badge: "Priya &middot; 10C",
        left: "Stage left",
        right: "Stage right",
        hazard: "Trip hazard tape",
        brief:
          "Priya is going into the middle of the school photo. The two rows either side are already lined up and the photographer has marked out a 360px by 240px space for her, chalked onto the floor.",
        gap: { width: 360, height: 240 },
        require: { padding: 20, border: 10, margin: 10 },
        boxSizing: "content-box",
      },
      {
        id: "fs04",
        difficulty: "easy",
        student: "Noah",
        badge: "Noah &middot; 10D",
        left: "Shelf A",
        right: "Shelf B",
        hazard: "Loose shelving",
        brief:
          "Noah's project box has to go on the library display between shelf A and shelf B. The shelves are fixed brackets, so the space they leave is exactly 280px by 160px.",
        gap: { width: 280, height: 160 },
        require: { padding: 8, border: 2, margin: 10 },
        boxSizing: "content-box",
      },
    ],
  },
  {
    id: "crowded-corridor",
    name: "Crowded Corridor",
    color: "#0891b2",
    levels: [
      {
        id: "fs05",
        difficulty: "medium",
        student: "Aisha",
        badge: "Aisha &middot; 10B",
        left: "Year 11",
        right: "Year 12",
        hazard: "A wet floor sign",
        brief:
          "Assembly seating puts Aisha between the Year 11 and Year 12 blocks. Both blocks are already seated, leaving her a 340px by 210px space and not one pixel more.",
        gap: { width: 340, height: 210 },
        require: { padding: 16, border: 3, margin: 6 },
        boxSizing: "content-box",
      },
      {
        id: "fs06",
        difficulty: "medium",
        student: "Ellis",
        badge: "Ellis &middot; 10A",
        left: "Servery",
        right: "Till",
        hazard: "A hot plate rail",
        brief:
          "The canteen queue runs between the servery and the till, and the space left for Ellis is 296px by 188px. The servery is plumbed in and the till is bolted down.",
        gap: { width: 296, height: 188 },
        require: { padding: 14, border: 6, margin: 12 },
        boxSizing: "content-box",
      },
      {
        id: "fs07",
        difficulty: "medium",
        student: "Jonah",
        badge: "Jonah &middot; 10C",
        left: "Kiln",
        right: "Drying rack",
        hazard: "The kiln vent",
        brief:
          "Jonah's workbench goes into the art room between the kiln and the drying rack. The floor markings give him 372px by 244px, and the kiln has not moved since 1994.",
        gap: { width: 372, height: 244 },
        require: { padding: 18, border: 7, margin: 9 },
        boxSizing: "content-box",
      },
      {
        id: "fs08",
        difficulty: "medium",
        student: "Sana",
        badge: "Sana &middot; 10D",
        left: "Seat 4A",
        right: "Seat 4C",
        hazard: "The aisle rail",
        brief:
          "Sana has seat 4B on the excursion bus. The seats either side are moulded into the frame, so her space is fixed at 318px by 222px.",
        gap: { width: 318, height: 222 },
        require: { padding: 11, border: 4, margin: 13 },
        boxSizing: "content-box",
      },
      {
        id: "fs09",
        difficulty: "medium",
        student: "Kofi",
        badge: "Kofi &middot; 10B",
        left: "Court edge",
        right: "Court edge",
        hazard: "The boundary line",
        brief:
          "Kofi is setting up the scoring table inside the marked square on the gym floor. The square is 260px by 260px and it is painted on, so arguing with it is not an option.",
        gap: { width: 260, height: 260 },
        require: { padding: 15, border: 5, margin: 10 },
        boxSizing: "content-box",
      },
    ],
  },
  {
    id: "tight-squeeze",
    name: "Tight Squeeze",
    color: "#d97706",
    levels: [
      {
        id: "fs10",
        difficulty: "hard",
        student: "Ruby",
        badge: "Ruby &middot; 10A",
        left: "Fire door",
        right: "Pipe run",
        hazard: "The fire escape strip",
        brief:
          "The only space left for Ruby's storage pod is between the fire door and the pipe run: 334px by 197px. Neither can be touched, and the numbers are not going to be friendly.",
        gap: { width: 334, height: 197 },
        require: { padding: 13, border: 7, margin: 17 },
        boxSizing: "content-box",
      },
      {
        id: "fs11",
        difficulty: "hard",
        student: "Leo",
        badge: "Leo &middot; 10C",
        left: "Server rack",
        right: "Server rack",
        hazard: "Live cabling",
        brief:
          "Leo's machine goes into the one free slot in the IT room racking. The slot measures 289px by 231px, and the racking is welded.",
        gap: { width: 289, height: 231 },
        require: { padding: 9, border: 12, margin: 6 },
        boxSizing: "content-box",
      },
      {
        id: "fs12",
        difficulty: "hard",
        student: "Zara",
        badge: "Zara &middot; 10D",
        left: "Prop store",
        right: "Lighting desk",
        hazard: "Cable trunking",
        brief:
          "Zara is building the set piece that sits between the prop store and the lighting desk. The stage plan allows 412px by 186px, which is wide and not at all tall.",
        gap: { width: 412, height: 186 },
        require: { padding: 21, border: 3, margin: 11 },
        boxSizing: "content-box",
      },
      {
        id: "fs13",
        difficulty: "hard",
        student: "Hana",
        badge: "Hana &middot; 10B",
        left: "Glasshouse",
        right: "Tool shed",
        hazard: "Glass panelling",
        brief:
          "Hana's garden bed goes between the glasshouse and the tool shed, into a plot measuring 275px by 255px. The glasshouse is the reason the clearance rule exists.",
        gap: { width: 275, height: 255 },
        require: { padding: 17, border: 8, margin: 14 },
        boxSizing: "content-box",
      },
      {
        id: "fs14",
        difficulty: "hard",
        student: "Marco",
        badge: "Marco &middot; 10A",
        left: "Kiln room",
        right: "Store room",
        hazard: "An open vent",
        brief:
          "The last space in the design workshop is 303px by 209px, wedged between two rooms that both have doors opening into it. Marco gets that space or none at all.",
        gap: { width: 303, height: 209 },
        require: { padding: 19, border: 6, margin: 13 },
        boxSizing: "content-box",
      },
    ],
  },
  {
    id: "border-box-bay",
    name: "Border-box Bay",
    color: "#7c3aed",
    levels: [
      {
        id: "fs15",
        difficulty: "medium",
        student: "Iris",
        badge: "Iris &middot; 10C",
        left: "Locker 21",
        right: "Locker 23",
        hazard: "A live edge",
        brief:
          "Same bay, new rule: this pod is measured border-box, so the width you set already includes the padding and the border. Only the margin is added on the outside. The gap is 320px by 200px.",
        gap: { width: 320, height: 200 },
        require: { padding: 12, border: 4, margin: 10 },
        boxSizing: "border-box",
      },
      {
        id: "fs16",
        difficulty: "medium",
        student: "Deng",
        badge: "Deng &middot; 10D",
        left: "Bay wall",
        right: "Bay wall",
        hazard: "A live edge",
        brief:
          "Deng's pod is border-box too, and the walls of the loading bay leave 360px by 240px. The padding and the border are inside the width now, so the only thing still added on the outside is the margin.",
        gap: { width: 360, height: 240 },
        require: { padding: 20, border: 5, margin: 15 },
        boxSizing: "border-box",
      },
      {
        id: "fs17",
        difficulty: "hard",
        student: "Freya",
        badge: "Freya &middot; 10B",
        left: "Cold store",
        right: "Dry store",
        hazard: "A refrigerant line",
        brief:
          "Freya's border-box pod goes between the cold store and the dry store, into 288px by 224px. Get the margin right and the rest of the sum is shorter than you think.",
        gap: { width: 288, height: 224 },
        require: { padding: 16, border: 8, margin: 12 },
        boxSizing: "border-box",
      },
      {
        id: "fs18",
        difficulty: "hard",
        student: "Otis",
        badge: "Otis &middot; 10A",
        left: "Pallet stack",
        right: "Pallet stack",
        hazard: "A live edge",
        brief:
          "The last slot in the yard is 344px by 212px, with a stack of pallets on either side. Otis's pod is border-box and the clearance rule out here is the strictest on site.",
        gap: { width: 344, height: 212 },
        require: { padding: 18, border: 6, margin: 19 },
        boxSizing: "border-box",
      },
    ],
  },
];
