/**
 * Match the CSS - quiz logic.
 * A sidebar lists two categories (HTML Elements, Whole Page), each a flat
 * list of questions, mirroring the HTML Structure Trainer's category
 * sidebar. Selecting a question renders a read-only HTML+CSS prompt and
 * five live-rendered <iframe srcdoc> previews built from the same HTML
 * with differently-tweaked CSS, exactly one of which matches the prompt.
 */

(function () {
  "use strict";

  const ACTIVITY_ID = "match-the-css";
  const STATE_KEY = "match_css_state_v2";
  const CHOICE_LETTERS = ["A", "B", "C", "D", "E"];

  // Whole-page previews render at a real desktop size, then get scaled
  // down to a thumbnail - the same trick real site-preview thumbnails use,
  // so what's shown is a genuine full page, just shrunk, not a cropped
  // fragment of one. Card/iframe pixel sizes are computed from these two
  // numbers alone (see applyFullPageSizing) so the ratio can't drift out
  // of sync between JS and CSS.
  const FULL_PAGE_VIEWPORT = { width: 1280, height: 900 };
  const FULL_PAGE_THUMB_WIDTH = 480;

  const state = {
    currentCategoryId: null,
    currentQuestionId: null,
    locked: false,
    answered: new Set(),
    correct: new Set(),
  };

  const dom = {
    sidebar: document.getElementById("sidebar"),
    categoryList: document.getElementById("categoryList"),
    totalCount: document.getElementById("totalCount"),
    progressCount: document.getElementById("progressCount"),
    progressFill: document.getElementById("progressFill"),
    titleBarBadge: document.getElementById("titleBarBadge"),
    titleBarTitle: document.getElementById("titleBarTitle"),
    promptDifficultyBadge: document.getElementById("promptDifficultyBadge"),
    btnNext: document.getElementById("btnNext"),
    promptHtml: document.getElementById("promptHtml"),
    promptCss: document.getElementById("promptCss"),
    choicesGrid: document.getElementById("choicesGrid"),
    feedbackNote: document.getElementById("feedbackNote"),
    welcomeState: document.getElementById("welcomeState"),
    welcomeStats: document.getElementById("welcomeStats"),
    quizGrid: document.getElementById("quizGrid"),
    completionPanel: document.getElementById("completionPanel"),
    completionScoreText: document.getElementById("completionScoreText"),
    btnRestart: document.getElementById("btnRestart"),
    zoomModal: document.getElementById("zoomModal"),
    zoomFrame: document.getElementById("zoomFrame"),
    zoomModalLabel: document.getElementById("zoomModalLabel"),
    btnZoomClose: document.getElementById("btnZoomClose"),
  };

  // ── Pure helpers ─────────────────────────────────────
  function escapeHtml(str) {
    const map = {
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#039;",
    };
    return str.replace(/[&<>"']/g, (c) => map[c]);
  }

  function shuffleArray(arr) {
    const shuffled = [...arr];
    for (let i = shuffled.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
  }

  /** Simple syntax highlighter for a small HTML snippet. */
  function highlightHtml(source) {
    let escaped = escapeHtml(source);

    escaped = escaped.replace(
      /(&lt;\/?)([\w-]+)((?:\s+[\w-]+(?:=&quot;[^&]*?&quot;)?)*\s*\/?)(&gt;)/g,
      (match, open, tag, attrs, close) => {
        let highlighted = `<span class="tag">${open}${tag}</span>`;
        if (attrs) {
          highlighted += attrs.replace(
            /([\w-]+)(=)(&quot;)(.*?)(&quot;)/g,
            '<span class="attr">$1</span>$2<span class="string">$3$4$5</span>'
          );
        }
        highlighted += `<span class="tag">${close}</span>`;
        return highlighted;
      }
    );

    return escaped;
  }

  /** A colour-picking helper: drop a small swatch right after every hex
   * colour in a (already-escaped) declaration value, so a value like
   * "#2563eb" shows what it actually looks like instead of asking the
   * reader to picture six hex digits. */
  function injectColorSwatches(escapedValue) {
    return escapedValue.replace(/#[0-9a-fA-F]{3,8}\b/g, (hex) => {
      return `${hex}<span class="color-swatch" style="background:${hex}" title="${hex}"></span>`;
    });
  }

  /**
   * Syntax highlighter for CSS generated by serializeCssRules: one
   * selector-opener line, one declaration per line, one closer line. Runs
   * line-by-line rather than one regex pass over the whole blob so a
   * selector like ".btn:hover {" is never mistaken for a declaration.
   */
  function highlightCss(source) {
    return source
      .split("\n")
      .map((line) => {
        const trimmed = line.trim();

        if (trimmed === "" || trimmed === "}") {
          return escapeHtml(line);
        }

        if (trimmed.endsWith("{")) {
          const selector = line.slice(0, line.lastIndexOf("{"));
          return `<span class="keyword">${escapeHtml(selector)}</span>{`;
        }

        const declMatch = trimmed.match(/^([\w-]+)\s*:\s*(.+?);?\s*$/);
        if (declMatch) {
          const indent = line.slice(0, line.length - line.trimStart().length);
          const hasSemicolon = trimmed.endsWith(";");
          const value = injectColorSwatches(escapeHtml(declMatch[2]));
          return `${indent}<span class="attr">${escapeHtml(
            declMatch[1]
          )}</span>: <span class="string">${value}</span>${hasSemicolon ? ";" : ""}`;
        }

        return escapeHtml(line);
      })
      .join("\n");
  }

  /** Turn a { rules: [{selector, decls}] } shape into real CSS text. */
  function serializeCssRules(rules) {
    return rules
      .map((rule) => {
        const body = Object.entries(rule.decls)
          .map(([prop, val]) => `  ${prop}: ${val};`)
          .join("\n");
        return `${rule.selector} {\n${body}\n}`;
      })
      .join("\n\n");
  }

  /** Shallow-merge per-selector property overrides onto a rule list. */
  function applyOverrides(rules, overridesBySelector) {
    if (!overridesBySelector) return rules;
    return rules.map((rule) => {
      const patch = overridesBySelector[rule.selector];
      return patch
        ? { selector: rule.selector, decls: { ...rule.decls, ...patch } }
        : rule;
    });
  }

  function cssTextForChoice(question, choice) {
    if (choice.cssOverride != null) return choice.cssOverride;
    return serializeCssRules(applyOverrides(question.css.rules, choice.overrides));
  }

  /** A minimal document for a preview iframe, linking the site's real
   * tokens so previews automatically match light/dark mode. A single
   * element centers in its preview; a whole page lays out top-to-bottom
   * like a real page and picks up a small reset (default UA margins on
   * headings/lists would otherwise fight the authored CSS). */
  function buildSrcdoc(html, cssText, isFullPage) {
    const layout = isFullPage
      ? `margin: 0; padding: 0; background: var(--bg-canvas); color: var(--text-primary); font-family: var(--font-sans);`
      : `margin: 0; padding: 0; min-height: 100%; display: flex; align-items: center; justify-content: center; background: var(--bg-canvas); color: var(--text-primary); font-family: var(--font-sans);`;
    const reset = isFullPage
      ? `h1, h2, h3, h4, p, ul, ol, li { margin: 0; padding: 0; } ul, ol { list-style: none; } a { text-decoration: none; color: inherit; }`
      : "";

    return `<!DOCTYPE html><html><head><meta charset="UTF-8" />
<link rel="stylesheet" href="../../assets/css/tokens.css" />
<style>
  *, *::before, *::after { box-sizing: border-box; }
  html, body { ${layout} }
  ${reset}
  a, button, input, textarea, select, form, label { pointer-events: none !important; }
</style>
<style>${cssText}</style>
</head><body>${html}</body></html>`;
  }

  function setDifficultyBadge(el, difficulty) {
    el.textContent = difficulty.charAt(0).toUpperCase() + difficulty.slice(1);
    el.classList.remove("difficulty-easy", "difficulty-medium", "difficulty-hard");
    el.classList.add(`difficulty-${difficulty}`);
  }

  // ── Category/question lookup ─────────────────────────
  function getAllQuestionIds() {
    const ids = new Set();
    MATCH_CSS_CATEGORIES.forEach((cat) => cat.questions.forEach((q) => ids.add(q.id)));
    return ids;
  }

  function flattenQuestions() {
    const flat = [];
    MATCH_CSS_CATEGORIES.forEach((category) => {
      category.questions.forEach((question) => flat.push({ category, question }));
    });
    return flat;
  }

  function findFirstUnanswered() {
    for (const category of MATCH_CSS_CATEGORIES) {
      for (const question of category.questions) {
        if (!state.answered.has(question.id)) return { category, question };
      }
    }
    return null;
  }

  /** Next unanswered question after the current one, wrapping around to
   * the start if everything after it is already answered. */
  function findNextUnanswered() {
    const flat = flattenQuestions();
    const fromIndex = flat.findIndex(
      (item) =>
        item.category.id === state.currentCategoryId && item.question.id === state.currentQuestionId
    );
    for (let i = fromIndex + 1; i < flat.length; i++) {
      if (!state.answered.has(flat[i].question.id)) return flat[i];
    }
    for (let i = 0; i <= fromIndex; i++) {
      if (!state.answered.has(flat[i].question.id)) return flat[i];
    }
    return null;
  }

  function buildWelcomeStats() {
    dom.welcomeStats.innerHTML = MATCH_CSS_CATEGORIES.map(
      (category) => `
        <div class="welcome-stat">
          <div class="welcome-stat-icon">&#9670;</div>
          <div class="welcome-stat-label">${category.questions.length} ${category.name}</div>
        </div>
      `
    ).join("");
  }

  // ── Sidebar ──────────────────────────────────────────
  function buildSidebar() {
    dom.categoryList.innerHTML = "";

    MATCH_CSS_CATEGORIES.forEach((category, catIdx) => {
      const group = document.createElement("div");
      group.className = "category-group";

      const header = document.createElement("div");
      header.className = "category-header" + (catIdx === 0 ? " expanded" : "");
      header.innerHTML = `
        <span>${category.name}</span>
        <span class="category-count">(${category.questions.length})</span>
        <span class="cat-chevron">&#9656;</span>
      `;

      const list = document.createElement("div");
      list.className = "category-problems" + (catIdx === 0 ? " open" : "");

      category.questions.forEach((question, qIdx) => {
        const item = document.createElement("div");
        item.className = "problem-item";
        item.dataset.questionId = question.id;
        item.dataset.categoryId = category.id;
        item.innerHTML = `
          <span class="status-dot"></span>
          <span>Question ${qIdx + 1}</span>
        `;
        item.addEventListener("click", () => loadQuestion(category, question));
        list.appendChild(item);
      });

      header.addEventListener("click", () => {
        header.classList.toggle("expanded");
        list.classList.toggle("open");
      });

      group.appendChild(header);
      group.appendChild(list);
      dom.categoryList.appendChild(group);
    });

    updateSidebarStates();
  }

  function updateSidebarStates() {
    document.querySelectorAll(".problem-item").forEach((el) => {
      const id = el.dataset.questionId;
      el.classList.toggle("solved", state.correct.has(id));
      el.classList.toggle("wrong", state.answered.has(id) && !state.correct.has(id));
      el.classList.toggle(
        "active",
        el.dataset.categoryId === state.currentCategoryId && id === state.currentQuestionId
      );
    });
  }

  // ── Rendering ────────────────────────────────────────
  function loadQuestion(category, question) {
    state.currentCategoryId = category.id;
    state.currentQuestionId = question.id;
    state.locked = false;

    const indexInCategory = category.questions.findIndex((q) => q.id === question.id);
    dom.titleBarBadge.textContent = category.name;
    dom.titleBarBadge.style.background = category.color + "22";
    dom.titleBarBadge.style.color = category.color;
    dom.titleBarTitle.textContent = `Question ${indexInCategory + 1}`;
    setDifficultyBadge(dom.promptDifficultyBadge, question.difficulty);

    dom.promptHtml.innerHTML = highlightHtml(question.html);
    dom.promptCss.innerHTML = highlightCss(serializeCssRules(question.css.rules));

    dom.feedbackNote.textContent = "";
    dom.btnNext.disabled = true;
    dom.quizGrid.classList.toggle("is-full-page", category.id === "whole-page");

    renderChoices(question, category);

    dom.welcomeState.style.display = "none";
    dom.quizGrid.style.display = "";
    dom.completionPanel.classList.remove("is-visible");

    updateSidebarStates();
  }

  /** Render the iframe at a real desktop size, then scale the whole thing
   * down so the card shows an exact thumbnail of the full page. Sizes the
   * whole .choice-item (head row + card), not just the card, so the head
   * row lines up at the same width. */
  function applyFullPageSizing(item, card, iframe) {
    const scale = FULL_PAGE_THUMB_WIDTH / FULL_PAGE_VIEWPORT.width;
    item.style.width = `${FULL_PAGE_THUMB_WIDTH}px`;
    card.style.width = `${FULL_PAGE_THUMB_WIDTH}px`;
    card.style.height = `${Math.round(FULL_PAGE_VIEWPORT.height * scale)}px`;
    iframe.style.width = `${FULL_PAGE_VIEWPORT.width}px`;
    iframe.style.height = `${FULL_PAGE_VIEWPORT.height}px`;
    iframe.style.transform = `scale(${scale})`;
  }

  /** Each choice is a small head row (letter + zoom button, sitting above
   * the preview so neither ever overlaps the page content being judged)
   * plus the actual clickable answer button below it. */
  function renderChoices(question, category) {
    dom.choicesGrid.innerHTML = "";
    const isFullPage = category.id === "whole-page";
    dom.choicesGrid.classList.toggle("is-full-page", isFullPage);

    const shuffled = shuffleArray(question.choices);

    shuffled.forEach((choice, i) => {
      const letter = CHOICE_LETTERS[i];
      const cssText = cssTextForChoice(question, choice);

      const item = document.createElement("div");
      item.className = "choice-item";
      item.dataset.choiceId = choice.id;

      const head = document.createElement("div");
      head.className = "choice-item-head";

      const label = document.createElement("span");
      label.className = "choice-label";
      label.textContent = `Option ${letter}`;

      const zoomBtn = document.createElement("button");
      zoomBtn.type = "button";
      zoomBtn.className = "choice-zoom-btn";
      zoomBtn.setAttribute("aria-label", `Zoom in on option ${letter}`);
      zoomBtn.innerHTML = "&#128269; Zoom";
      zoomBtn.addEventListener("click", () => openZoomModal(question, choice, letter, isFullPage));

      head.appendChild(label);
      head.appendChild(zoomBtn);

      const card = document.createElement("button");
      card.type = "button";
      card.className = "choice-card";
      card.setAttribute("aria-label", `Select option ${letter}`);

      const iframe = document.createElement("iframe");
      iframe.setAttribute("sandbox", "");
      iframe.title = `Preview ${letter}`;
      iframe.srcdoc = buildSrcdoc(question.html, cssText, isFullPage);
      if (isFullPage) applyFullPageSizing(item, card, iframe);

      card.appendChild(iframe);
      card.addEventListener("click", () => handleChoiceClick(item, choice.id, question));

      item.appendChild(head);
      item.appendChild(card);
      dom.choicesGrid.appendChild(item);
    });
  }

  /** Show one choice at (near) real size in a modal, since the thumbnail
   * grid deliberately shrinks pages down and a 10px difference at that
   * scale can be genuinely hard to judge - zooming in shows it at 1:1. */
  function openZoomModal(question, choice, letter, isFullPage) {
    const cssText = cssTextForChoice(question, choice);
    dom.zoomFrame.srcdoc = buildSrcdoc(question.html, cssText, isFullPage);
    dom.zoomModal.classList.toggle("is-full-page", isFullPage);
    dom.zoomModalLabel.textContent = `Option ${letter}`;
    dom.zoomModal.classList.add("is-open");
  }

  function closeZoomModal() {
    dom.zoomModal.classList.remove("is-open");
    dom.zoomFrame.srcdoc = "";
  }

  // ── Grading ──────────────────────────────────────────
  function handleChoiceClick(itemEl, choiceId, question) {
    if (state.locked) return;
    state.locked = true;

    const isCorrect = choiceId === question.correctChoiceId;

    dom.choicesGrid.querySelectorAll(".choice-item").forEach((item) => {
      item.querySelector(".choice-card").disabled = true;
      if (item.dataset.choiceId === question.correctChoiceId) {
        item.classList.add("correct");
      }
    });

    if (!isCorrect) itemEl.classList.add("incorrect");

    state.answered.add(question.id);
    if (isCorrect) state.correct.add(question.id);

    if (question.explain) {
      dom.feedbackNote.textContent = question.explain;
    }

    saveState();
    updateProgress();
    dom.btnNext.disabled = false;
  }

  function handleNextClick() {
    const next = findNextUnanswered();
    if (next) {
      loadQuestion(next.category, next.question);
    } else {
      showCompletion();
    }
  }

  function updateProgress() {
    const total = getAllQuestionIds().size;
    const correctCount = state.correct.size;
    const pct = Math.round((correctCount / total) * 100);

    dom.progressCount.textContent = `${correctCount}/${total}`;
    dom.progressFill.style.width = pct + "%";
    dom.progressFill.classList.toggle("is-complete", pct >= 100);

    if (window.WDFBProgress) window.WDFBProgress.setPercent(ACTIVITY_ID, pct);

    updateSidebarStates();
  }

  function showCompletion() {
    dom.quizGrid.style.display = "none";
    dom.completionPanel.classList.add("is-visible");
    dom.completionScoreText.textContent = `You scored ${state.correct.size} out of ${
      getAllQuestionIds().size
    } across both categories.`;
    state.currentCategoryId = null;
    state.currentQuestionId = null;
    updateSidebarStates();
  }

  function restartQuiz() {
    state.answered = new Set();
    state.correct = new Set();
    saveState();
    updateProgress();

    const first = findFirstUnanswered();
    loadQuestion(first.category, first.question);
  }

  // ── Persistence ──────────────────────────────────────
  function loadState() {
    try {
      const raw = localStorage.getItem(STATE_KEY);
      if (!raw) return;
      const saved = JSON.parse(raw);
      const validIds = getAllQuestionIds();
      (saved.answered || []).forEach((id) => {
        if (validIds.has(id)) state.answered.add(id);
      });
      (saved.correct || []).forEach((id) => {
        if (validIds.has(id)) state.correct.add(id);
      });
    } catch (e) {
      /* ignore */
    }
  }

  function saveState() {
    try {
      localStorage.setItem(
        STATE_KEY,
        JSON.stringify({ answered: [...state.answered], correct: [...state.correct] })
      );
    } catch (e) {
      /* ignore */
    }
  }

  // ── Init ─────────────────────────────────────────────
  function init() {
    if (window.WDFBProgress) window.WDFBProgress.markViewed(ACTIVITY_ID);

    loadState();
    dom.totalCount.textContent = getAllQuestionIds().size;
    buildSidebar();
    buildWelcomeStats();
    updateProgress();

    dom.btnNext.addEventListener("click", handleNextClick);
    dom.btnRestart.addEventListener("click", restartQuiz);
    dom.btnZoomClose.addEventListener("click", closeZoomModal);
    dom.zoomModal.addEventListener("click", (e) => {
      if (e.target === dom.zoomModal) closeZoomModal();
    });
    document.addEventListener("keydown", (e) => {
      if (e.key === "Escape" && dom.zoomModal.classList.contains("is-open")) {
        closeZoomModal();
      }
    });

    // Mirrors the HTML Structure Trainer: never auto-load a problem, even
    // a partly-solved learner still picks where to start from the sidebar.
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
