/* Fit the Cargo - level data: each slot's fixed size and the padding, border and margin its load demands. */
const FIT_CARGO_CATEGORIES = [
  {
    id: "loading-bay",
    name: "Loading Bay",
    color: "#2563eb",
    levels: [
      {
        id: "fc01",
        difficulty: "easy",
        cargo: "glassware",
        badge: "Glassware &middot; Fragile",
        left: "Crate 11",
        right: "Crate 13",
        hazard: "Wet paint",
        brief:
          "A crate of glassware is going out on tonight's run, and the only space left on the pallet is between crate 11 and crate 13. Both are already strapped down, so the slot stays exactly 320px wide and 200px tall no matter what you do.",
        gap: { width: 320, height: 200 },
        require: { padding: 10, border: 5, margin: 15 },
        boxSizing: "content-box",
      },
      {
        id: "fc02",
        difficulty: "easy",
        cargo: "ceramics",
        badge: "Ceramics &middot; Handle with care",
        left: "Pallet A",
        right: "Pallet B",
        hazard: "Fresh varnish",
        brief:
          "The ceramics have to travel between pallet A and pallet B, which leaves a slot of 300px by 180px. Both pallets are shrink-wrapped to the deck and the loader is not unwrapping them for you.",
        gap: { width: 300, height: 180 },
        require: { padding: 12, border: 4, margin: 14 },
        boxSizing: "content-box",
      },
      {
        id: "fc03",
        difficulty: "easy",
        cargo: "telescope lens",
        badge: "Telescope lens &middot; Fragile",
        left: "Rack left",
        right: "Rack right",
        hazard: "Strapping tape",
        brief:
          "A telescope lens is being shipped to the observatory in the middle bay of the racking. The racking is bolted to the floor and the bay it leaves is 360px by 240px.",
        gap: { width: 360, height: 240 },
        require: { padding: 20, border: 10, margin: 10 },
        boxSizing: "content-box",
      },
      {
        id: "fc04",
        difficulty: "easy",
        cargo: "vinyl records",
        badge: "Vinyl records &middot; Keep flat",
        left: "Shelf A",
        right: "Shelf B",
        hazard: "Loose shelving",
        brief:
          "A box of vinyl records has to sit on the van shelf between shelf A and shelf B. The shelves are welded brackets, so the space they leave is exactly 280px by 160px.",
        gap: { width: 280, height: 160 },
        require: { padding: 8, border: 2, margin: 10 },
        boxSizing: "content-box",
      },
    ],
  },
  {
    id: "freight-deck",
    name: "Freight Deck",
    color: "#0891b2",
    levels: [
      {
        id: "fc05",
        difficulty: "medium",
        cargo: "lab samples",
        badge: "Lab samples &middot; Keep cold",
        left: "Freight 11",
        right: "Freight 12",
        hazard: "A coolant line",
        brief:
          "The lab samples are booked onto the freight deck between two containers that are already sealed and manifested. The slot they leave is 340px by 210px and not one pixel more.",
        gap: { width: 340, height: 210 },
        require: { padding: 16, border: 3, margin: 6 },
        boxSizing: "content-box",
      },
      {
        id: "fc06",
        difficulty: "medium",
        cargo: "chilled produce",
        badge: "Chilled produce &middot; 4&deg;C",
        left: "Chiller",
        right: "Bulkhead",
        hazard: "A hot pipe",
        brief:
          "The produce crate goes between the chiller unit and the bulkhead, into a slot of 296px by 188px. The chiller is plumbed in and the bulkhead is the side of the truck.",
        gap: { width: 296, height: 188 },
        require: { padding: 14, border: 6, margin: 12 },
        boxSizing: "content-box",
      },
      {
        id: "fc07",
        difficulty: "medium",
        cargo: "fired tiles",
        badge: "Fired tiles &middot; Brittle",
        left: "Kiln",
        right: "Drying rack",
        hazard: "The kiln vent",
        brief:
          "A pallet of fired tiles waits for collection between the kiln and the drying rack. The floor markings give it 372px by 244px, and the kiln has not moved since 1994.",
        gap: { width: 372, height: 244 },
        require: { padding: 18, border: 7, margin: 9 },
        boxSizing: "content-box",
      },
      {
        id: "fc08",
        difficulty: "medium",
        cargo: "camera gear",
        badge: "Camera gear &middot; Fragile",
        left: "Case 4A",
        right: "Case 4C",
        hazard: "The aisle rail",
        brief:
          "The camera gear is flying as hold luggage in slot 4B. The cases either side are moulded into the loading frame, so the space is fixed at 318px by 222px.",
        gap: { width: 318, height: 222 },
        require: { padding: 11, border: 4, margin: 13 },
        boxSizing: "content-box",
      },
      {
        id: "fc09",
        difficulty: "medium",
        cargo: "scoreboard",
        badge: "Scoreboard &middot; Do not stack",
        left: "Bay edge",
        right: "Bay edge",
        hazard: "The painted boundary",
        brief:
          "The scoreboard crate has to sit inside the square painted on the depot floor. The square is 260px by 260px and it is painted on, so arguing with it is not an option.",
        gap: { width: 260, height: 260 },
        require: { padding: 15, border: 5, margin: 10 },
        boxSizing: "content-box",
      },
    ],
  },
  {
    id: "tight-hold",
    name: "Tight Hold",
    color: "#d97706",
    levels: [
      {
        id: "fc10",
        difficulty: "hard",
        cargo: "spare parts",
        badge: "Spare parts &middot; Heavy",
        left: "Fire door",
        right: "Pipe run",
        hazard: "The fire escape strip",
        brief:
          "The only space left in the hold for the spare parts is between the fire door and the pipe run: 334px by 197px. Neither can be touched, and the numbers are not going to be friendly.",
        gap: { width: 334, height: 197 },
        require: { padding: 13, border: 7, margin: 17 },
        boxSizing: "content-box",
      },
      {
        id: "fc11",
        difficulty: "hard",
        cargo: "server blade",
        badge: "Server blade &middot; Antistatic",
        left: "Server rack",
        right: "Server rack",
        hazard: "Live cabling",
        brief:
          "The server blade ships in the one free slot in the racking, which measures 289px by 231px. The racking is welded and the cabling either side is live.",
        gap: { width: 289, height: 231 },
        require: { padding: 9, border: 12, margin: 6 },
        boxSizing: "content-box",
      },
      {
        id: "fc12",
        difficulty: "hard",
        cargo: "stage lighting",
        badge: "Stage lighting &middot; Fragile",
        left: "Prop store",
        right: "Lighting desk",
        hazard: "Cable trunking",
        brief:
          "The lighting crate goes between the prop store and the lighting desk. The stage plan allows 412px by 186px, which is wide and not at all tall.",
        gap: { width: 412, height: 186 },
        require: { padding: 21, border: 3, margin: 11 },
        boxSizing: "content-box",
      },
      {
        id: "fc13",
        difficulty: "hard",
        cargo: "seedlings",
        badge: "Seedlings &middot; This way up",
        left: "Glasshouse",
        right: "Tool shed",
        hazard: "Glass panelling",
        brief:
          "The seedling trays travel in the plot between the glasshouse and the tool shed, measuring 275px by 255px. The glasshouse is the reason the clearance rule exists.",
        gap: { width: 275, height: 255 },
        require: { padding: 17, border: 8, margin: 14 },
        boxSizing: "content-box",
      },
      {
        id: "fc14",
        difficulty: "hard",
        cargo: "workshop tools",
        badge: "Workshop tools &middot; Heavy",
        left: "Kiln room",
        right: "Store room",
        hazard: "An open vent",
        brief:
          "The last space in the workshop store is 303px by 209px, wedged between two rooms that both have doors opening into it. The tool crate gets that space or none at all.",
        gap: { width: 303, height: 209 },
        require: { padding: 19, border: 6, margin: 13 },
        boxSizing: "content-box",
      },
    ],
  },
  {
    id: "border-box-freight",
    name: "Border-box Freight",
    color: "#7c3aed",
    levels: [
      {
        id: "fc15",
        difficulty: "medium",
        cargo: "medical kit",
        badge: "Medical kit &middot; Priority",
        left: "Crate 21",
        right: "Crate 23",
        hazard: "A live edge",
        brief:
          "Same bay, new rule: this crate is measured border-box, so the width you set already includes the packing foam and the crate wall. Only the clearance is added on the outside. The slot is 320px by 200px.",
        gap: { width: 320, height: 200 },
        require: { padding: 12, border: 4, margin: 10 },
        boxSizing: "border-box",
      },
      {
        id: "fc16",
        difficulty: "medium",
        cargo: "engine block",
        badge: "Engine block &middot; Heavy",
        left: "Bay wall",
        right: "Bay wall",
        hazard: "A live edge",
        brief:
          "The engine block ships border-box too, and the walls of the loading bay leave 360px by 240px. The padding and the border are inside the width now, so the only thing still added on the outside is the margin.",
        gap: { width: 360, height: 240 },
        require: { padding: 20, border: 5, margin: 15 },
        boxSizing: "border-box",
      },
      {
        id: "fc17",
        difficulty: "hard",
        cargo: "frozen stock",
        badge: "Frozen stock &middot; -18&deg;C",
        left: "Cold store",
        right: "Dry store",
        hazard: "A refrigerant line",
        brief:
          "The frozen stock is border-box and goes between the cold store and the dry store, into 288px by 224px. Get the clearance right and the rest of the sum is shorter than you think.",
        gap: { width: 288, height: 224 },
        require: { padding: 16, border: 8, margin: 12 },
        boxSizing: "border-box",
      },
      {
        id: "fc18",
        difficulty: "hard",
        cargo: "marble slab",
        badge: "Marble slab &middot; Do not tilt",
        left: "Pallet stack",
        right: "Pallet stack",
        hazard: "A live edge",
        brief:
          "The last slot in the yard is 344px by 212px, with a stack of pallets on either side. The marble crate is border-box and the clearance rule out here is the strictest on site.",
        gap: { width: 344, height: 212 },
        require: { padding: 18, border: 6, margin: 19 },
        boxSizing: "border-box",
      },
    ],
  },
];
