/* Fit the Cargo - level data: each slot's fixed size and the padding, border and margin its load demands. */
const FIT_CARGO_CATEGORIES = [
  {
    id: "loading-bay",
    name: "Loading Bay",
    color: "#2563eb",
    levels: [
      {
        id: "fc01",
        difficulty: "easy",
        cargo: "glassware",
        left: "Crate 11",
        right: "Crate 13",
        hazard: "Wet paint",
        brief:
          "A crate of glassware is going out on tonight's run, and the only space left on the pallet is between crate 11 and crate 13. Both are already strapped down, so the slot stays exactly 320px wide and 200px tall no matter what you do.",
        gap: { width: 320, height: 200 },
        require: { padding: 10, border: 5, margin: 15 },
        boxSizing: "content-box",
      },
      {
        id: "fc02",
        difficulty: "easy",
        cargo: "ceramics",
        left: "Pallet A",
        right: "Pallet B",
        hazard: "Fresh varnish",
        brief:
          "The ceramics have to travel between pallet A and pallet B, which leaves a slot of 300px by 180px. Both pallets are shrink-wrapped to the deck and the loader is not unwrapping them for you.",
        gap: { width: 300, height: 180 },
        require: { padding: 12, border: 4, margin: 14 },
        boxSizing: "content-box",
      },
      {
        id: "fc03",
        difficulty: "easy",
        cargo: "telescope lens",
        left: "Rack left",
        right: "Rack right",
        hazard: "Strapping tape",
        brief:
          "A telescope lens is being shipped to the observatory in the middle bay of the racking. The racking is bolted to the floor and the bay it leaves is 360px by 240px.",
        gap: { width: 360, height: 240 },
        require: { padding: 20, border: 10, margin: 10 },
        boxSizing: "content-box",
      },
      {
        id: "fc04",
        difficulty: "easy",
        cargo: "vinyl records",
        left: "Shelf A",
        right: "Shelf B",
        hazard: "Loose shelving",
        brief:
          "A box of vinyl records has to sit on the van shelf between shelf A and shelf B. The shelves are welded brackets, so the space they leave is exactly 280px by 160px.",
        gap: { width: 280, height: 160 },
        require: { padding: 8, border: 2, margin: 10 },
        boxSizing: "content-box",
      },
    ],
  },
  {
    id: "freight-deck",
    name: "Freight Deck",
    color: "#0891b2",
    levels: [
      {
        id: "fc05",
        difficulty: "medium",
        cargo: "lab samples",
        left: "Freight 11",
        right: "Freight 12",
        hazard: "A coolant line",
        brief:
          "The lab samples are booked onto the freight deck between two containers that are already sealed and manifested. The slot they leave is 340px by 210px and not one pixel more.",
        gap: { width: 340, height: 210 },
        require: { padding: 16, border: 3, margin: 6 },
        boxSizing: "content-box",
      },
      {
        id: "fc06",
        difficulty: "medium",
        cargo: "chilled produce",
        left: "Chiller",
        right: "Bulkhead",
        hazard: "A hot pipe",
        brief:
          "The produce crate goes between the chiller unit and the bulkhead, into a slot of 296px by 188px. The chiller is plumbed in and the bulkhead is the side of the truck.",
        gap: { width: 296, height: 188 },
        require: { padding: 14, border: 6, margin: 12 },
        boxSizing: "content-box",
      },
      {
        id: "fc07",
        difficulty: "medium",
        cargo: "fired tiles",
        left: "Deck rail",
        right: "Bulkhead",
        hazard: "An exhaust vent",
        brief:
          "A pallet of fired tiles is lashed to the freight deck between the deck rail and the bulkhead. The lashing points give it 372px by 244px, and neither the rail nor the bulkhead is going anywhere.",
        gap: { width: 372, height: 244 },
        require: { padding: 18, border: 7, margin: 9 },
        boxSizing: "content-box",
      },
      {
        id: "fc08",
        difficulty: "medium",
        cargo: "camera gear",
        left: "Case 4A",
        right: "Case 4C",
        hazard: "The aisle rail",
        brief:
          "The camera gear is flying as hold luggage in slot 4B. The cases either side are moulded into the loading frame, so the space is fixed at 318px by 222px.",
        gap: { width: 318, height: 222 },
        require: { padding: 11, border: 4, margin: 13 },
        boxSizing: "content-box",
      },
      {
        id: "fc09",
        difficulty: "medium",
        cargo: "scoreboard",
        left: "Deck edge",
        right: "Deck edge",
        hazard: "The painted boundary",
        brief:
          "The scoreboard crate has to sit inside the square painted on the freight deck. The square is 260px by 260px and it is painted on, so arguing with it is not an option.",
        gap: { width: 260, height: 260 },
        require: { padding: 15, border: 5, margin: 10 },
        boxSizing: "content-box",
      },
    ],
  },
  {
    id: "container-yard",
    name: "Container Yard",
    color: "#d97706",
    levels: [
      {
        id: "fc10",
        difficulty: "hard",
        cargo: "spare parts",
        left: "Stack 40",
        right: "Stack 42",
        hazard: "A crane lane",
        brief:
          "Out in the container yard the spare parts have to go into the one space left in row 40, between two stacks that are four containers high. The space is 334px by 197px, and the numbers are not going to be friendly.",
        gap: { width: 334, height: 197 },
        require: { padding: 13, border: 7, margin: 17 },
        boxSizing: "content-box",
      },
      {
        id: "fc11",
        difficulty: "hard",
        cargo: "server blade",
        left: "Reefer 7",
        right: "Reefer 9",
        hazard: "A power lead",
        brief:
          "The server blade waits in the yard between two refrigerated containers, which are plugged in and humming. The space they leave is 289px by 231px and the power leads run along both edges.",
        gap: { width: 289, height: 231 },
        require: { padding: 9, border: 12, margin: 6 },
        boxSizing: "content-box",
      },
      {
        id: "fc12",
        difficulty: "hard",
        cargo: "stage lighting",
        left: "Flat rack",
        right: "Flat rack",
        hazard: "A lashing chain",
        brief:
          "The lighting crate is going on a flat rack in the yard, in the gap between two loads already chained down. The gap is 412px by 186px, which is wide and not at all tall.",
        gap: { width: 412, height: 186 },
        require: { padding: 21, border: 3, margin: 11 },
        boxSizing: "content-box",
      },
      {
        id: "fc13",
        difficulty: "hard",
        cargo: "seedlings",
        left: "Stack 18",
        right: "Stack 20",
        hazard: "A drainage channel",
        brief:
          "The seedling trays are booked into the shaded row of the yard, in a space of 275px by 255px between two stacks. Everything here is stacked by crane, so nothing shifts to make room.",
        gap: { width: 275, height: 255 },
        require: { padding: 17, border: 8, margin: 14 },
        boxSizing: "content-box",
      },
      {
        id: "fc14",
        difficulty: "hard",
        cargo: "workshop tools",
        left: "Stack 03",
        right: "Gate house",
        hazard: "A truck lane",
        brief:
          "The last space in the yard is 303px by 209px, wedged between the end stack and the gate house, with trucks turning past it all day. The tool crate gets that space or none at all.",
        gap: { width: 303, height: 209 },
        require: { padding: 19, border: 6, margin: 13 },
        boxSizing: "content-box",
      },
    ],
  },
  {
    id: "air-freight",
    name: "Air Freight",
    color: "#7c3aed",
    levels: [
      {
        id: "fc15",
        difficulty: "medium",
        cargo: "medical kit",
        left: "ULD 21",
        right: "ULD 23",
        hazard: "A tie-down rail",
        brief:
          "Air freight, new rule: this crate is measured border-box, so the width you set already includes the packing foam and the crate wall. Only the clearance is added on the outside. The space in the hold is 320px by 200px.",
        gap: { width: 320, height: 200 },
        require: { padding: 12, border: 4, margin: 10 },
        boxSizing: "border-box",
      },
      {
        id: "fc16",
        difficulty: "medium",
        cargo: "engine block",
        left: "Hold wall",
        right: "Hold wall",
        hazard: "A cargo net",
        brief:
          "The engine block ships border-box too, and the curved walls of the aircraft hold leave 360px by 240px. The padding and the border are inside the width now, so the only thing still added on the outside is the margin.",
        gap: { width: 360, height: 240 },
        require: { padding: 20, border: 5, margin: 15 },
        boxSizing: "border-box",
      },
      {
        id: "fc17",
        difficulty: "hard",
        cargo: "frozen stock",
        left: "Cool ULD",
        right: "Dry ULD",
        hazard: "A refrigerant line",
        brief:
          "The frozen stock is border-box and flies between a cooled container and a dry one, in a space of 288px by 224px. Get the clearance right and the rest of the sum is shorter than you think.",
        gap: { width: 288, height: 224 },
        require: { padding: 16, border: 8, margin: 12 },
        boxSizing: "border-box",
      },
      {
        id: "fc18",
        difficulty: "hard",
        cargo: "marble slab",
        left: "Air pallet",
        right: "Air pallet",
        hazard: "A tie-down rail",
        brief:
          "The last space on the aircraft pallet run is 344px by 212px, with a loaded pallet either side. The marble crate is border-box and the clearance rule up here is the strictest anywhere.",
        gap: { width: 344, height: 212 },
        require: { padding: 18, border: 6, margin: 19 },
        boxSizing: "border-box",
      },
    ],
  },
];
